version: '3'
services:
  qx:
    image: "itisfoundation/qooxdoo-compiler:${VERSION_TAG:-0.2.10}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - version=${VERSION_TAG:-0.2.10}
    volumes:
      - '.:/home/node/src'
    ports:
      - '8080:8080'
    working_dir: /home/node/src/${APP_DIR}
    command: serve