version: '3'
services:
  qxcompiler:
    image: itisfoundation/qxcompiler
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/node/src
    volumes:
      - '.:/home/node/src'
    ports:
      - '8080:8080'
